
Carbon:
  IncludeAssets:
    Path:
      Inline:
        CSS: 'Public/Frontend/css'
        JS: 'Public/Frontend/lib'
      File:
        CSS: 'Public/Frontend/css'
        JS: 'Public/Frontend/lib'
    # Asset files who get's loaded in live and backend view
    General:
      Head:
        - main.css
      Body:
        - main.js
